apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kong
  namespace: kong
spec:
  interval: 1m
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  chart:
    spec:
      chart: kong
      version: "2.47.0"
      sourceRef:
        kind: HelmRepository
        name: kong
  interval: 5m
  values:
    ingressController:
      install: true
      env:
        feature_gates: RewriteURIs=true
    proxy:
      type: LoadBalancer 
