apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/podinfo

patches:
  - target:
      kind: KongIngress
      name: podinfo-ingress
    path: patch-ingress.yaml