apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/podinfo

patches:
  - target:
      kind: Ingress
      metadata:
      name: podinfo-ingress
      namespace: default
    path: patch-ingress.yaml