apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-rate-limited-ingress
  namespace: default
  annotations:
    konghq.com/protocol: "http"
    konghq.com/override: podinfo-strip
    konghq.com/plugins: "podinfo-ratelimit"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /podinfo/version
        pathType: Prefix
        backend:
          service:
            name: podinfo
            port:
              number: 9898
