apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: default
  annotations:
    konghq.com/protocol: "http"
    konghq.com/override: podinfo-strip
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /podinfo
        pathType: Prefix
        backend:
          service:
            name: podinfo
            port:
              number: 9898 
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: podinfo-strip
  namespace: default
route:
  strip_path: true
  regex_priority: 100
  paths:
    - ~/podinfo(/.*)