apiVersion: networking.k8s.io/v1
kind: KongPlugin
metadata:
  name: podinfo-ratelimit
  namespace: default
config:
  minute: 1  # 1 req/minute
  policy: local  # Locally stores req info
  limit_by: ip
plugin: rate-limiting
