apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: default
  annotations:
    konghq.com/protocol: "http"
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - host: podinfo.local
      http:
        paths:
          - path: /version  
            pathType: Prefix
            annotations:
              konghq.com/plugins: podinfo-ratelimit
            backend:
              service:
                name: podinfo-service
                port:
                  number: 80
